run_metadata:
  default_input_namespace: dwest77a
  description: Better Kerchunk
  script: ~/venvs/bkvenv/bin/python3.10 test_convert.py
  remote_repo: https://github.com/dwest77a/better_kerchunk

write:
- data_product: outs/
  description: 
  file_type: csv

- data_product: kstores/*.json
  description: Kerchunk JSON Meta Stores
  file_type: json

- data_product: kfiles/*.json
  description: Kerchunk JSON Input Files
  file_type: json

- data_product: kstores/*.nc
  description: Kerchunk NetCDF variable stores
  file_type: NetCDF4