git:
  local_repo: /home/dwest77/Documents/better_kerchunk
  remote: origin
  remote_repo: https://github.com/cedadev/better_kerchunk.git
namespaces:
  input: dwest77a
  output: dwest77a
registries:
  origin:
    data_store: https://data.fairdatapipeline.org/data/
    token: /home/dwest77/.fair/cli/remotetoken.txt
    uri: https://data.fairdatapipeline.org/api/
user:
  email: dwest77a@users.noreply.github.com
  family_name: Westwood
  github: dwest77a
  given_names: Daniel
  name: Daniel Westwood
  uri: https://github.com/dwest77a
